### ISSUE TITLE
Source Code Formatting

### ISSUE THREAD

**Issue by knepley** [bueler/p4pdes#1]
How are you doing it? It looks like you use \inputwhole{} which I have never seen. I am using lstlisting. Is there a reason you did not use this? I would like to standardize, and am willing to listen to argument, but I hate to keep changing.

**Comment by bueler** [comment]
Good point.  I'll probably change over to `lstlisting`, which I have not used.  `\inputwhole{}` and such are my macros around calls to `fancyvrb` stuff.  What do you want to standardize?

**Comment by knepley** [comment]
On Thu, Sep 24, 2015 at 2:21 PM, Ed Bueler notifications@github.com wrote:

> Good point. I'll probably change over to lstlisting, which I have not
> used. \inputwhole{} and such are my macros around calls to fancyvrb
> stuff. What do you want to standardize?
> 
> I wanted to standardize the way we display code in LaTeX since I expect to
> be writing a lot of things with lots of code.
> 
> —
> 
> Reply to this email directly or view it on GitHub
> https://github.com/bueler/p4pdes/issues/1#issuecomment-143024345.

## 

What most experimenters take for granted before they begin their
experiments is infinitely more interesting than any results to which their
experiments lead.
-- Norbert Wiener

**Comment by bueler** [comment]
Looking at `listings` now I see why, a year or so ago, I did not choose it.  For now I'll stick to `fancyvrb`, which has inferior appearance but better features, as follows.

I want to show parts of codes, not whole codes, generally.  (`\inputwhole{}` is one of several macros I have, which wrap `VerbatimInput()`; the rest of these macros show parts ...)

I do _not_ want to display part of a source code "from line N to line M" because then editing the examples changes the line numbers and requires editing the LaTeX include statement.  So I use `FancyVerb[Start|Stop]String`, and a comment in the source code itself.  This functionality seems not to be in any of the listings-type LaTeX packages.

**Comment by ckhroulev** [comment]
Seems like `listings` can typeset code read in by `fancyvrb`. See section 5.13 (page 41) of [the listings manual](http://mirror.hmc.edu/ctan/macros/latex/contrib/listings/listings.pdf).

**Comment by bueler** [comment]
I can make it sort of work, but the frame is hard to control, in particular.  The only thing I really seem to be gaining is italicized comments.  What was I trying to accomplish?  :smile:

**Comment by knepley** [comment]
On Thu, Sep 24, 2015 at 3:42 PM, Ed Bueler notifications@github.com wrote:

> Looking at listings now I see why, a year or so ago, I did not choose it.
> For now I'll stick to fancyvrb, which has inferior appearance but better
> features, as follows.
> 
> I want to show parts of codes, not whole codes, generally. (\inputwhole{}
> is one of several macros I have, which wrap VerbatimInput(); the rest of
> these macros show parts ...)
> 
> I do _not_ want to display part of a source code "from line N to line M"
> because then editing the examples changes the line numbers and requires
> editing the LaTeX include statement. So I use FancyVerb[Start|Stop]String,
> and a comment in the source code itself. This functionality seems not to be
> in any of the listings-type LaTeX packages.

I am trying to understand the user case. What exactly do you want to do
with \lising{} that it does not do?

  Thanks,

```
 Matt
```

 —

> Reply to this email directly or view it on GitHub
> https://github.com/bueler/p4pdes/issues/1#issuecomment-143045168.

## 

What most experimenters take for granted before they begin their
experiments is infinitely more interesting than any results to which their
experiments lead.
-- Norbert Wiener

**Comment by bueler** [comment]
I have a code that I want to include but which I only want to show a part of, namely the part between `//START` and `//STOP`:

```
#include <petsc.h>
int main(int argc, char **args) {
//START
  PetscInitialize(&argc,&args,NULL,"Compute e in parallel with PETSc.\n\n");
  PetscFinalize();
//STOP
  return 0;
}
```

so the displayed source is just

```
  PetscInitialize(&argc,&args,NULL,"Compute e in parallel with PETSc.\n\n");
  PetscFinalize();
```

Apparently `listings` requires that I know the line numbers, but these change as I edit the C source.

There are many ways to deal with this issue, but one of the simplest is to not use `listings`.  Why is it that you want to impose uniformity on the world here?

**Comment by knepley** [comment]
On Thu, Sep 24, 2015 at 5:51 PM, Ed Bueler notifications@github.com wrote:

> I have a code that I want to include but which I only want to show a part
> of, namely the part between //START and //STOP:
> 
> #include <petsc.h>
> int main(int argc, char **args) {
> //START
>   PetscInitialize(&argc,&args,NULL,"Compute e in parallel with PETSc.\n\n");
>   PetscFinalize();
> //STOP
>   return 0;
> }
> 
> so the displayed source is just
> 
>   PetscInitialize(&argc,&args,NULL,"Compute e in parallel with PETSc.\n\n");
>   PetscFinalize();
> 
> Apparently listings requires that I know the line numbers, but these
> change as I edit the C source.
> 
> There are many ways to deal with this issue, but one of the simplest is to
> not use listings. Why is it that you want to impose uniformity on the
> world here?
> 
> I want a single way to configure how our code looks, and really a single
> definition of the look of PETSc code. There seems to be
> no good reason to have multiple ways to do this.

You want file extraction, which fancyvrb provides, but it does not
highlight keywords, or differentiate comments, etc. And as
pointed out, we can use fancyvrb for the extraction and listings for the
typesetting. I am fine with using another typesetter, but
it has to be widely available, and its has to do code highlighting based on
language.

   Matt

> —
> Reply to this email directly or view it on GitHub
> https://github.com/bueler/p4pdes/issues/1#issuecomment-143070098.

## 

What most experimenters take for granted before they begin their
experiments is infinitely more interesting than any results to which their
experiments lead.
-- Norbert Wiener

**Comment by bueler** [comment]
> ... a single definition of the look of PETSc code. There seems to be
> no good reason to have multiple ways to do this.

I agree with the need for a better look.  Seems like the PETSc User's Manual could lead the way.
