### ISSUE TITLE
Preface and Getting started (nitpicking)

### ISSUE THREAD

**Issue by ckhroulev** [bueler/p4pdes#2]
Here are some comments (using revision 58a575b). (You said "I would welcome any kind of feedback", right?)
-  [tex/preface.tex:8](https://github.com/bueler/p4pdes/blob/58a575b/tex/preface.tex#L8)

``` latex
 and probably some in \Matlab or python
```

The name of the programming language Python should be capitalized (judging by the way it is spelled on www.python.org).
-  [tex/preface.tex:12](https://github.com/bueler/p4pdes/blob/58a575b/tex/preface.tex#L12)

``` latex
 Use \texttt{git} to get the example C codes
```

"Git" should be capitalized also.
-  [tex/preface.tex:62](https://github.com/bueler/p4pdes/blob/58a575b/tex/preface.tex#L62)

``` latex
 passing arguments by value and reference, 
```

The C language does not have the concept of a reference: in C we can pass arguments by value or by pointer.

The Wikipedia page on the C language states that [Pass-by-reference is simulated in C by explicitly passing pointer values.](https://en.wikipedia.org/wiki/C_%28programming_language%29#Overview)
-  [tex/preface.tex:76](https://github.com/bueler/p4pdes/blob/58a575b/tex/preface.tex#L76)

``` latex
 Finally, this book assumes a \emph{bash} shell
```

According to its official webpage Bash should be capitalized.
-  [tex/getstarted.tex:16](https://github.com/bueler/p4pdes/blob/58a575b/tex/getstarted.tex#L16)

``` latex
   We will return to this ``trace-back'' mechanism later in the Chapter.
```

Add a FIXME or something like `\ref{FIXME}` (this way LaTeX will keep reminding you about a broken reference).
-  [tex/getstarted.tex:32](https://github.com/bueler/p4pdes/blob/58a575b/tex/getstarted.tex#L32)

``` latex
   If it is not already installed on your machine, go to
 \begin{quote}
 \href{http://www.mcs.anl.gov/petsc/download/index.html}{\texttt{www.mcs.anl.gov/petsc/download/}}
 \end{quote}
 to download the source code
```

Consider creating a `\newcommand` to make it easier to update URLs such as this one.
-  [tex/getstarted.tex:124](https://github.com/bueler/p4pdes/blob/58a575b/tex/getstarted.tex#L124)

``` latex
 A traceback is a list of the nested methods, in reverse order
```

Technically these are "nested function calls" or "nested stack frames" (there are no methods in C).
-  [tex/getstarted.tex:131](https://github.com/bueler/p4pdes/blob/58a575b/tex/getstarted.tex#L131)

``` latex
  on  $N$ processors
```

Very, very minor: consider using "processor" only when referring to physical processors and "process" otherwise.

**Comment by bueler** [comment]
Cool, much appreciated.  Somehow I thought C99 allowed true pass-by-reference ... but I am not using it.
