### ISSUE TITLE
make sure codes are double <--> quad portable?

### ISSUE THREAD

**Issue by bueler** [bueler/p4pdes#4]
Barry's comments on this:

> >    ch1/e.c   you have chosen to use PetscReal, but not PetscInt, PetscMPIInt etc however in the MPI calls you use MPI_DOUBLE MPI_SUM instead of MPIU_REAL, MPIU_SUM which are actually needed for quad precision; so the benefit of PetscReal doesn't really exist. I suggest actually just using double (and no special PETSc types like PetscReal) and just expand your discussion of complex numbers to say that PETSc can be built to use single, double, quad precisions and 32 or 64 bit integers but for simplicity sake all your codes are just double with 32 bit integers.
> 
> Although this gives me "permission" to use double, which would indeed improve the look of my codes, in fact I am not sure I want to give up on having my codes also work in quad precision.

The reason I suggested not doing that is you need the ugly MPIU_stuff (see below) or quad doesn't work and the MPIU_stuff is confusing to new PETSc users. Note that if your code does NO MPI message passing or Allreducing then you don't need any MPIU_stuff.

> So:  Is there a "how to write a petsc code that is double-->quad portable" doc or man page somewhere?

Sadly, not really. I should add something in the users manual.

>  For example, I am not sure how switching to quad would affect addressing and int types, if at all, but (I think) you are hinting it does.

int size has nothing to do with quad and doesn't affect addressing either

>  And direct MPI calls have no flexibility about number types?

The issue is that MPI does not know anything about quad precision at all. Thus MPI_SUM, MPI_MAX etc don't work with quad precision. One needs to use the PETSc provided MPIU_SUM etc and one needs to use MPIU_REAL instead of MPI_DOUBLE; when using quad precision MPIU_REAL is a PETSc defined MPI data type. When using double precision MPIU_REAL is MPI_DOUBLE.  One also needs to use a quad precision BLAS/LAPACK; the only one I know about is our own --download-f2cblaslapack.

**Comment by bueler** [comment]
notes to self:
- indeed my machine, and most modern machines, have `int` set to 32 bit integers
- and `PetscInt=int` on my machine
- if desired, the in-place substitution is accomplished by
  
  ```
  sed -i -e 's/PetscInt/int/g' -e 's/PetscReal/double/g' mycode.c
  ```
  
  but there would then be alignment/formatting stuff to fiddle with
- the substitution was tested successfully on `c/ch5/solns/cartoon.c` and `c/ch5/plap.c`

**Comment by bueler** [comment]
Because `grep PetscReal *.tex` returns a few hits in `tex/`, I am not done.  Also check `PetscInt` and `PetscScalar`.

**Comment by bueler** [comment]
@psanan  I am curious about your input on this.  I don't know if MPIU_... issues are different now than in 2015 when Barry made the comments at top.  (And:  Much appreciate your input already!!)

**Comment by psanan** [comment]
I would argue pretty strongly for the use of the proper PETSc datatypes for everything! 

The library is designed around them, and beyond being able to change the precision (single/double/quad) and scalar field (real/complex), they provide useful abstractions alongside the higher-level linear algebra types. Any user is going to need to understand what these types are as soon as they so much as read a man page. All existing PETSc examples and tutorials use them.

For the purposes of the book giving a gentle introduction, maybe you can advise the reader that it's generally safe to think of these like `double` and `int`, while starting out. 

Is the only rationale for not using the proper datatypes to avoid having to explain the usage of `MPIU_*` in one example? I don't think that's sufficient justification: this is the correct way to use MPI calls in PETSc code and while it's added complication, it's also a common "gotcha" so is valuable to teach people about. In terms of trying to make the first example as gentle as possible, I would suggest to heavily comment the source to point out the fact that these `MPIU_*` constructs are used - people are usually fine with copy-pasting this kind of thing, even if they don't understand or care about the motivation.

Maybe this could even be the basis for a quick exercise, assuming that at some point in the book you tell people about `gdb` (not sure if you do). In that case, it's pretty easy to let someone directly check out what the base datatype and precision is for a variable, e.g. 
```
$ gdb ./ex23
[...]
(gdb) b 30
Breakpoint 1 at 0x1a0f: file ex23.c, line 30.
(gdb) r
Starting program: /home/patrick/code/petsc/src/ksp/ksp/examples/tutorials/ex23
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, main (argc=1, args=0x7fffffffe768) at ex23.c:31
31	  PetscInt       i,n = 10,col[3],its,rstart,rend,nlocal;
(gdb) ptype n
type = int
(gdb) call sizeof(n)
$1 = 4
```

**Comment by bueler** [comment]
1. I am convinced.  I will do a big search-and-replace for double and int.  (Also I will actually *think* about this issue, which I decided not to think about back when.)

2. I learned something about gdb.

Thanks!

**Comment by bueler** [comment]
Note to self:  For the PETSc official line on MPIU_... see the PETSc man pages for MPIU_REAL, MPIU_SUM, PetscReal, PetscScalar.

**Comment by psanan** [comment]
Note that during the find-replace, presumably there would be some situations where some of the `int`s would become `PetscInt`s, and some would become `PetscMPIInt`s.

**Comment by bueler** [comment]
This was done.
