### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by QwZhang** [bueler/p4pdes#50]
Hi, 

It seems be to `info->my-1` instead of `info->my` in this line:
https://github.com/bueler/p4pdes/blob/5f6aca9b94380549eb7744349635a92d0af787c7/c/ch5/heat.c#L101
Am I right?
Qw

**Comment by bueler** [comment]
I think that line is correct.  In the periodic direction the number of nodes and the number of subintervals are equal.  That is, the number of _distinct_ nodes is `my`, and each node should be understood as starting a _distinct_ subintervals.  See Figure 5.6; the x-direction is not periodic, and therefore different.

Thanks for the comment.  I will close the issue now, but feel free to re-open if you think I should address it more.
