### ISSUE TITLE
Error in the exercise solution code: expected expression before ‘do’

### ISSUE THREAD

**Issue by thw1021** [bueler/p4pdes#54]
Dear Bueler,

There is something wrong with the following code
https://github.com/bueler/p4pdes/blob/19805f8ed5bde805dae744804cf0fd8fcf1c7199/c/ch1/solns/expx.c#L14-L16
When I try to compile it with `make expx`, I got an error
```
/home/tang/petsc/arch-linux-c-debug/bin/mpicc -o expx.o -c -Wall -Wwrite-strings -Wno-unknown-pragmas -Wno-lto-type-mismatch -fstack-protector -fvisibility=hidden -g3 -O0 -pedantic -std=c99 -I/home/tang/petsc/include -I/home/tang/petsc/arch-linux-c-debug/include    `pwd`/expx.c
In file included from /home/tang/petsc/include/petscsys.h:1274,
                 from /home/tang/petsc/include/petscbag.h:5,
                 from /home/tang/petsc/include/petsc.h:5,
                 from /home/tang/secondDisk/p4pdes-3.18.0/c/ch1/solns/expx.c:1:
/home/tang/secondDisk/p4pdes-3.18.0/c/ch1/solns/expx.c: In function ‘main’:
/home/tang/petsc/include/petscoptions.h:182:5: error: expected expression before ‘do’
  182 |     do { \
      |     ^~
/home/tang/secondDisk/p4pdes-3.18.0/c/ch1/solns/expx.c:15:10: note: in expansion of macro ‘PetscOptionsBegin’
   15 |   ierr = PetscOptionsBegin(PETSC_COMM_WORLD,"","options for expx",""); CHKERRQ(ierr);
      |          ^~~~~~~~~~~~~~~~~
make: *** [/home/tang/petsc/lib/petsc/conf/rules:285: expx.o] Error 1
```
Following the book, the compilation can be finished by removing the `ierr`
```
  PetscOptionsBegin(PETSC_COMM_WORLD, "", "options for expx", "");
  PetscOptionsReal("-x", "input to exp(x) function", "expx.c", x, &x, PETSC_NULL);
  PetscOptionsEnd();
```

OS: ubuntu 20.04
PETSc version: 3.18.1

Could you confirm it, please?

Best regards

**Comment by thw1021** [comment]
I also tried some other solution codes and got the same error. ([this one](https://github.com/bueler/p4pdes/blob/master/c/ch8/solns/lntwo.c), for example)

**Comment by bueler** [comment]
Thanks for pointing this out!  I forgot to update `solns/` codes when the significant change in PETSc error-checking style occurred, which was 3.17 I guess.  Now Chapter 1-4 are done; in those Chapters you should be able to compile the codes without trouble if you `git pull` so you have current `master` branch.  Let me know if there are any issues now.  (I'll keep working on Chapters 5-12 over the next couple of days.)

**Comment by bueler** [comment]
@thw1021 As far as I know this is done in *all Chapters 1-12*.  Can you close the issue if you agree?  Thanks.

**Comment by thw1021** [comment]
Sure, thanks for your work.
